apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
      - services
      - replicationcontrollers
      - serviceaccounts
      - configmaps
      - secrets
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["get", "list"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["get", "list"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
    verbs: ["get", "list"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:  ["get", "list", "watch", "create"]
