sonar.projectKey=my-app
sonar.projectName=my-app
sonar.host.url=http://localhost:9000
sonar.login= sqp_a0ab7a2995002a4f9c509aef3f4979ebb5fdc65b
sonar.sources=.
sonar.exclusions=Helm/**
sonar.python.version=3
