grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 15d
    resources:
      requests:
        memory: 400Mi
      limits:
        memory: 800Mi

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

