{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\nsum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le,pod)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\nsum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le,pod)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(flask_http_request_duration_seconds_count) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"flask-app\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"flask-app\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}