pipeline {
  agent none

  stages {

    stage('Back-end (CI)') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        dir('multi-stage-multi-agent/backend') {
          sh '''
            mvn clean compile
            java -cp target/classes HelloWorld
          '''
        }
      }
    }

    stage('Front-end (CI)') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }

    stage('Deploy (CD)') {
      agent any
      steps {
        dir('multi-stage-multi-agent') {
          sh '''
            ansible-playbook -i ansible/inventory ansible/deploy.yml
          '''
        }
      }
    }

  }
}
:
