kubectl apply -f image-updater.yaml
git add image-updater.yaml
git commit -m "feat: add image updater"
git pushapiVersion: argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: flask-app
      commonUpdateSettings:
        updateStrategy: latest
        allowTags: "regexp:^[a-f0-9]{7,40}$"
      images:
        - alias: flask
          imageName: fahd81/flask-nginx
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
  writeBackConfig:
    method: git
    gitConfig:
      repository: https://github.com/fahdahmadee072-wq/Jenkins-Zero-To-Hero.git
      branch: main
      writeBackTarget: Helm/flask-nginx/values.yaml
