replicaCount: 1

image:
  repository: fahd81/flask-nginx
  tag: "fcc94934b2c00baa268769c5e469fc011f92b9ed"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: fahdtech.store
  tls:
    enabled: true
    secretName: flask-tls
    clusterIssuer: letsencrypt-production

resources:
  requests:
    cpu: "100m"
  limits:
    cpu: "300m"

env:
  FLASK_ENV: "production"
  DEBUG: "false"
  LOG_LEVEL: "info"
  DB_HOST: "fahd-postgres.postgres.database.azure.com"
  DB_NAME: "flaskdb"
  OTEL_SERVICE_NAME: "flask-app"
secret:
  POSTGRES_DB: sandbox
  POSTGRES_USER: flaskuser@fahd-postgres
  POSTGRES_PASSWORD: flaskpassword

autoscaling:
  enabled: false   # for now
  minReplicas: 1
  maxReplicas: 3
