FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY app.py .
ENV PORT=5000
EXPOSE 5000
CMD ["gunicorn", "--preload",  "app:app", "--bind", "0.0.0.0:5000", "--workers=2"]
